language: node_js
node_js:
- 14
addons:
  chrome: stable
before_script:
- sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
- sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
script:
- npm run build || travis_terminate 1;
- |
  if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run test-browserstack || travis_terminate 1;
  else
    npm run test || travis_terminate 1;
  fi;
- npm run docs || travis_terminate 1;
- zip -r jsdoc.zip docs || travis_terminate 1;
before_deploy:
- cd dist
deploy:
- provider: npm
  email: support@mapwize.io
  api_key:
    secure: HWN04W5ntgLw2rmLMX4xJfDAvobDxXAaoshmRzH23mXhnUfsfilxqUoJXShfTonjZ/6iWH3ei9svtuW9bxlwdDNvb5hkZB2QIDZDsCd7UCyE8vFZDjAqtiqUcNnh0rX/o6r4D5ayi+ji96tgzKe1LIJeZdAqd+cs9MM9aJdxyaRrgjthdrvy4e55VfKduK0PJBQLgP0piApCzQvA6VoxFcHQF4GljWHZfAPle/ZzmNy1q5Bbq6TcfJSFPOZFi4dPB1ryNRCJzU3Xb8cE+CYbjQ6QJidkOqm/IO3O0638NwlZeyGK10SDU88azail0epuzI6u5msmbn2TWj5W443OGipn0wKaF4aZ/whKB0I6Mr/DqASbR6j8ivnLoLi9hJEukIUBbc0mmJxy1GNmTU1FWbVBoeIm2H0dvVPbu/nU6nhMPyNVoAxQsboB4Be9Iq3KF/pph9f1NtO1FUe7+haOr7adTs1Idg6LfKRoFRMkAwRHUVIAE1dlqFSZGYmjk/y6TbmAZsuKLO8Ro5MafGe7GkTcMQwHZua/LsXp/yVZGwnWi1Z2WCCSPnVE3y+EqpO33XDB5Zwnw7akuYoD1ISBO4VhTTu8gNmNK8FJfuzKwkrjnJXcOXrD4J0wbfR0enLgE+RdnTYFCk3L5/z5frB6HsFnejuFh5ijJAkWRhHgWnU=
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "../jsdoc.zip"
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- cd ..
