language: node_js
node_js:
- 14
addons:
  chrome: stable
before_script:
- sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
- sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
script:
- npm run build || travis_terminate 1;
- |
  if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run test-browserstack || travis_terminate 1;
  else
    npm run test || travis_terminate 1;
  fi;
- npm run docs || travis_terminate 1;
- zip -r jsdoc.zip docs || travis_terminate 1;
before_deploy:
- cd dist
deploy:
- provider: npm
  email: support@mapwize.io
  api_key:
    secure: HWN04W5ntgLw2rmLMX4xJfDAvobDxXAaoshmRzH23mXhnUfsfilxqUoJXShfTonjZ/6iWH3ei9svtuW9bxlwdDNvb5hkZB2QIDZDsCd7UCyE8vFZDjAqtiqUcNnh0rX/o6r4D5ayi+ji96tgzKe1LIJeZdAqd+cs9MM9aJdxyaRrgjthdrvy4e55VfKduK0PJBQLgP0piApCzQvA6VoxFcHQF4GljWHZfAPle/ZzmNy1q5Bbq6TcfJSFPOZFi4dPB1ryNRCJzU3Xb8cE+CYbjQ6QJidkOqm/IO3O0638NwlZeyGK10SDU88azail0epuzI6u5msmbn2TWj5W443OGipn0wKaF4aZ/whKB0I6Mr/DqASbR6j8ivnLoLi9hJEukIUBbc0mmJxy1GNmTU1FWbVBoeIm2H0dvVPbu/nU6nhMPyNVoAxQsboB4Be9Iq3KF/pph9f1NtO1FUe7+haOr7adTs1Idg6LfKRoFRMkAwRHUVIAE1dlqFSZGYmjk/y6TbmAZsuKLO8Ro5MafGe7GkTcMQwHZua/LsXp/yVZGwnWi1Z2WCCSPnVE3y+EqpO33XDB5Zwnw7akuYoD1ISBO4VhTTu8gNmNK8FJfuzKwkrjnJXcOXrD4J0wbfR0enLgE+RdnTYFCk3L5/z5frB6HsFnejuFh5ijJAkWRhHgWnU=
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "../jsdoc.zip"
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- cd ..
env:
  global:
  - secure: PWEnNYo6nVV6aV3HtgtGfKvuZYQreoI20wr9jPd9NKgFdfQWKwAV8WbN0TAdvCQ+SvVdwtzerEQESHwhVPZLYVluQU4OagYrkLECdh3bepy42pKAD/AxNL8ypTvkG20Kq48YxK4cFeerLuBGPgTAi2HzqHNNzyf7CJ3WTQLvCSSDyLhOPeQ2Uu56tkHxTWC8DagTvjBVw49s4ylzUQ6+WhDI0nUpVhP5DYRc96cD4l7wNDTF5KEtuRRNBdtRDHtsxrOiUwXX9iGPb39szhC102x/mYAxp5NBsx4201R3f1qmC44Nh1avrkxJi3AX9VNG/yIgaJB5jQk9AMA5FKd3GI385writWOa14/+RmhcBtti8FKJaDY62QghDmRIqsSxE0vidAP4ra0jbV6TxWrTLMqaX6mngx6k6GRpdRZE/8HH8ie2M5qGRgBKTQ/PbcPiisj/LY9aj7kbrG1HJ+tkiNBVCRHe3P6Uz1Uj7jLMqXvkzaaDoM/UyPz0/cpoy4wZbjaJCV+Y6jNmyHp+DAtpB9b7kgruS+mWzvSgN3Igcw49ltWfGviXAQUYOSBLtpYgNZsMDDqhmsyLKHare+kd9LBeNN9KM7Lv2aJtmNOaKI5poKbs5QWmmy/9Nc2H70/JNWnvSWk5HvoI2/u1bmUypJCqkRgKxuvJXLqUFJ/m6lM= # GITHUB_TOKEN
  - secure: OfEe6h5mHjjLyO0sP3vEC07sioFdK48OxPD7YBbGGz6m+7PUFzD7HYEXq/APJfncP+M6+n8Axz8oshsllA1r2j94XPhepLQ/EyvFLt3lcfZA3tiTZGeJUNZrNqOYgr7UJ+RMah3dN60tWMBdOgak/ImSY9dxusD10Jczo5p42dH4c1s9jKdqc6+2eUMtni5ZgWG6nb0U+3EBKMhUcpVWC/2mkJrlzg8ssoT5kUOHqYIl0kqI8yp0YJCHsA1JhLOpzZXv0UZY6Tkqh+lEQhiF3bQs8fCKF/4QpMe2qT8UqZm2QsXcAP7gDhlC6boamQd/YNMSJyeINhKdBz+oK5eZoio1SVc7C6Zq46ZmQjw4FnMctk9Bh4cUYH2qkrENAnKgRnsnsl5i3rLsk0QSjzrMF6uEGJbr2WxbFG0ix5peamoJ/oele4gxmK+gIgjK03FTLGSoKNbrC00TkqVc6wTrgeJeRKEwNX+OzAR66XwD1Euv0/ssmFYrJZwGOycL2sAbWbFFiQYyeQei/S0qe13W7M3Kn0oMGpZ5EXKYd0pTf7HK2IYHEpkVwLn8H1z3vLVKV6F11AUJLyb3YM/6OEg+ynD2OZ+RBfxbc4cJYr62Mfzq1ABeQy2HU8MxocMzm/pyqUJcDFyxUR/2LaPLoUcU4avyO/QhBv5a9vdfdq4o+Uo= # BROWSERSTACK_USERNAME
  - secure: gy3mHYguA+Nuhue7WiAiBoe7kQ60AV3XyRnju2C1UZ8xC8l73iN19kb0o8/x1Ych5A+E8ZSwbLLHRbJ/KEqS3r97GrxTAPtGxJLkT7BQBIHGvuwxsW5v2Fq6hvGyTh76rTah49mloiyBBHV692daTFETrA/q1qdyCSQMwxyHiMVf8iITfhMs9pkmsXASXYcS+/9vREsE2t/hH74d2iqrEDgfUjcaeP0pKe1hnnl57YfxLKb3nbBQhbwsHpidW0pu1CANond3wlrka0yPesSknrH4JEbwhtmEapeSQ4CeujyDnPtz9TxYIiXBg/brfV8GBGLP7aAA6QrVofyXJlbhD0BD4TWJlRoLZFWCBJejJdwvsHkWOJXn3xwWPRCMJh7YvH3P0K1F2wuczMm2R0JW1orKE2XP37JtXRI4aH82dnB3mMl78coP6pkURMQP/0wfsLIwmiUoKZW06ux/HwWDrcMtbI4qkY0klIUX7bAK/Xvg5vS9lvAAPdBozaed0JHRvX7blQ0HF5FN4SffdEaBrTcBPpCjPjtHpfvwGtP42FaUJ8rTdObl5BdgNw7gVpvz3yyVCIEdZfNIzpUTNSA++cdMyG4WyTEF70VZmH+yLCqDJF/PFjcMmFw8Bwgn8BO2IQ8KsT+YAMJ0wT3V/Mj/gvaPxZVGOjOpoUGHuj1xX4k= # BROWSERSTACK_ACCESS_KEY
